import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Slider from './components/slider.js'
import Info from './components/info.js'
import { IoIosArrowRoundBack } from "react-icons/io";
import { IoIosArrowRoundForward } from "react-icons/io";
import ladyImage2 from './assets/1.jpg';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HDXDEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class={styles.container}>
          
          <div class={styles.b}> 
             <IoIosArrowRoundBack class={styles.back} size={80} color="gray"/>
             <div class={styles.infoTextTitlex}>
                    <IoIosArrowRoundForward class={styles.forward} size={80} color="gray" />
                </div>
             <Slider styles={styles}/>
          </div>
          <div class={styles.b}> 
             <Info styles={styles}/>
          </div>


      </main>
    </div>
  )
}
